version: '3.9'
services:
 slack_bot_service:
  container_name: slack_bot
  image: slack_bot_image:latest
  environment:
   - SLACKBOT_IP_PORT=http://slack_bot:4444
  cpus: 1
  mem_limit: 256m
  ports:
   - "4444:4444"
